### ISSUE TITLE
Not able to see the Azure Tag information

### ISSUE THREAD

**Issue by berryvanesch** [Microsoft/peek#26]
Hi, 

Peek is a nice tool and give us a good feeling on the Azure spending's for our customers.
But is it possible to figger out what the cost is for a specific resource, for example we have a couple of virtual machine and we need to now what the spending's are of this virtual machines. I thought we can use the Tags on a Virtual Machine but i'm not able to see tag information in peek and can't find the tag information in the database or in the webinterface XXXX.azurewebsites.net/swagger. 

Can you tell me if this is possible?

Regards,
Berry

**Comment by UtkarshVIT** [comment]
Hi Berry 
At the time of publication of this repo the APIs only returned _Resource type_ level cumulative data and not of individual resources. Thus, we can visualize cumulative data for each resource type.  Currently we are working on how to access resource level data.

**Comment by berryvanesch** [comment]
Hi UtkarshVIT,

Thank you for your reply.
Is there a date when this function is deployed? If you need a tester you can contact me.

Regards,
Berry

**Comment by berryvanesch** [comment]
Hi UtkarshVIT, 

I mean when detailed resource usages is available in Microsoft Peek.

Regards,
Berry
