### ISSUE TITLE
Asking for Azure subscription 

### ISSUE THREAD

**Issue by s3banerjee** [Microsoft/peek#31]
Hi , 

I ' ve created the Azurebilling Analytics project in visual studio -2015 -enterprise in my laptop , build was successful , was trying to publish the project through webAPI and just after that it is looking for credentials and i 've put the active azure subscription , but in next drop down it is asking for Azure subscription and nothing coming in the drop down. Any insight please . 

please let me know, if you are looking for any more information.
 
Looking forward for the update. 

Thanks, 

Saurabh

**Comment by UtkarshVIT** [comment]
Hello Saurabh 
Can you share the screenshots? you can also email it to me at utkarsh.sharma@microsoft.com

**Comment by s3banerjee** [comment]
Thanks Utkasrh , my issue is resolved , as subscription value was reduce to 0 , issue resolved now.
