### ISSUE TITLE
Unable to load AzureBillingAnalytics in Visual Studio Professional

### ISSUE THREAD

**Issue by GloveNinja217** [Microsoft/peek#35]
Hey there,

I'm trying to deploy Peek in our environment since the source code for AUBI is so broken that I can't get it to work. That being said, when I try to load the project into Visual Studio I get the following error:
"We were unable to automatically populate your Visual Studio Team Services accounts.
The following error was encountered: TF400813: Resource not available for anonymous access. Client authentication required."

Alternatively, when I moved the Peek-Master folder to a different location on my PC, I received this error when attempting to open it:
"The mappings for the solution could not be found.
The active solution has been temporarily disconnected from source control because the server is unavailable.  To attempt to reconnect to source control, close and then re-open the solution when the server is available.  If you want to connect this solution to another server, use the Change Source Control dialog."

I don't work in Visual Studio typically so if these are simple issues I apologies for not knowing how to resolve this, but if you could help me I would really like to deploy this in my environment.

**Comment by UtkarshVIT** [comment]
Hi 
I downloaded the solution and built in on Visual Studio(Enterprise 2015) and all 3 projects built successfully. Also, all web projects are getting deployed successfully with the correct credentials. 
I am not sure how are you deploying the solution. Can you please elaborate? There is a [deployment ](https://github.com/Microsoft/peek/blob/master/Documentation/DeploymentSteps.md)guide available in the repo. I request you to use the visual studio deployment method.

**Comment by ssugar** [comment]
I've been able to clone this repo, open in VS 2015 and can build the projects.
