### ISSUE TITLE
How to get the daily consumption 

### ISSUE THREAD

**Issue by s3banerjee** [Microsoft/peek#40]
Hi , 

Can you please help us to know , how we can get the daily consumption which will be of  current day or few days back , any process elaboration will be helpful ? 

Thanks , 

Saurabh

**Comment by snpdev** [comment]
Hi Saurabh,

Please see the issue https://github.com/Microsoft/peek/issues/38. Is your issue the same?

**Comment by s3banerjee** [comment]
Hi Snpdev,

My understanding is also same that CspBillingData and CspSummaryData contain data for invoiced consumption.

CspUsageData table contains data for the coming billing period.Though i was running from last 3-4 days there is no change in the column Sum (value) for QuantityUsed and TotalCost of the CspUsageData , that too for client/customer who are using csp portal heavily.

Any views /comments please.

Thanks,

Saurabh

**Comment by UtkarshVIT** [comment]
Hi Saurabh
Currently we are built on the _Usage_ namespace. The daily data for a resource is available through the now released _Consumption_ namespace. We will be updating PEEK to incorporate this

**Comment by s3banerjee** [comment]
Hi Utkarsh,

Thanks for above update , so with above incorporation we will getting the daily usage and latency issue is resolved and on daily usage we will be getting back following information also along with dates. 

•	resource category, and/or
•	resource tag name(s) and value(s), and/or


Thanks, 

Saurabh

**Comment by s3banerjee** [comment]
Hi Utkarsh, 

We have seen some update from below link in the cspUtlization, but it is throwing exception of timeout , is that already for use ? 

https://github.com/Microsoft/peek/tree/implimentUtilization

looking forward for the update please. 

Thanks,

Saurabh

**Comment by UtkarshVIT** [comment]
Hi Saurabh!
We are still working on it. Is the API project returning timeout exception when you run it your locally on swagger?

**Comment by s3banerjee** [comment]
Hi Utkasrh, 

Thanks for clarification, yes we are using swagger (while got the code is uploaded in Azure) and got the timeout ,  one quick question any rough idea  by when it will be ready for implementation. 

Thanks,

Saurabh

**Comment by UtkarshVIT** [comment]
Hi! Things are expected to be ready by end of this month. Can you share how much time does it take for data to be fetched while the code is run locally?

**Comment by s3banerjee** [comment]
Hi Utkarsh, 

Thanks for update ,

We upload the code in Azure and run the webjob , for fetching data from 01-2017 having 3 API's 

a. cspBilling 
b. cspusage 
c. cspsummary

generally takes around 5-6 min and even some time less, even it has fetch the data in 3-4 min while we are doing testing. 

What should be general performance , how much time it should take ? 

Please let me know, if you are looking for any more clarification. 

Thanks,

**Comment by UtkarshVIT** [comment]
Azure web apps have a maximum timeout of 4 minutes which cannot be increased. If the deployed APIs take more than 4 minutes to return we get a 50x timeout error. 
Since we have programmed the APIs to be async, we can't find another way to optimize API performance. Incase the APIs exceed the time limit, we have to reengineer the web job to use the utilization namespace directly. 
In the test account that we are using, the data fetching is happening in under 3 minutes. Incase it is taking over 4 minutes(which you can know by deploying the APIs locally by pressing the start button in API project) then reengineering is required.

**Comment by mlautenbach** [comment]
@UtkarshVIT 
Hi, could you please update the status on this issue. 
We are also very interested in having the ability to view our daily consumption (within the Usage API) and being able to relate the usage to specific resources using Tags/resource names.

**Comment by UtkarshVIT** [comment]
Hi @mlautenbach 
Please check the latest code, we are now collecting daily utilization data. The visualizations are currently in the pipeline. Incase you can share some custom visualization you have created, it'll be of great help.
