### ISSUE TITLE
Display Tags of ressources

### ISSUE THREAD

**Issue by pbaumgartner** [Microsoft/peek#42]
Dear All

Is it planned to get a overview which ressources have which tags assigned?

Thanks
P

**Comment by UtkarshVIT** [comment]
Yes! The utilization API provides the tags, we are working on it.

**Comment by hyung-bin** [comment]
Hello,
when will this feature of displaying tags be released?

Thanks

Hyung-Bin

**Comment by UtkarshVIT** [comment]
Hi! We have created the code base for it in the [Implement Utilization ](https://github.com/Microsoft/peek/tree/implimentUtilization)branch. Preparing the visualizations for it. Feel free to contribute/ suggest any improvements in the code/ visualizations.

**Comment by pbaumgartner** [comment]
Is this implemented now with the latest update? If yes, is it possible to "update" a deployed Peek configuration or is it required to deploy everything again?

Thanks
P
